# Generated by Django 3.2.8 on 2021-10-29 13:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 13, 21, 52, 446817, tzinfo=utc)),
        ),
    ]
